\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';
BEGIN;
TRUNCATE TABLE public."acciones", public."act_economicas", public."actividades", public."anios", public."aprendizajes", public."asistencias", public."aspectos_evaluacion", public."aspectos_evaluacion_estudiantes", public."calendarios", public."capacidades_terminales", public."capacidades_terminales_estudiantes", public."carreras", public."dato_general", public."ejes_transversales", public."especialidades", public."evaluaciones", public."evaluaciones_estudiantes", public."evento_ocurrencias", public."evento_recurrencias", public."evento_relaciones", public."eventos", public."familias", public."fases", public."fases_metodos", public."fases_recursos", public."fases_tecnicas", public."grupo_modulos", public."grupos", public."horarios", public."indicadores_capacidad", public."indicadores_capacidad_estudiantes", public."matricula_grupos", public."matricula_paquetes", public."matricula_users", public."matriculas", public."metodos", public."modulo_videos", public."modulos", public."modulos_estudiantes", public."paquete_grupos", public."paquete_modulos", public."paquetes", public."personal_especialidades", public."personales", public."planes", public."posts", public."publicacion_videos", public."publicaciones", public."recordatorios", public."recursos", public."roles", public."sectores", public."semestres", public."tecnicas", public."tipo_carreras", public."turnos", public."unidades_didacticas", public."unidades_didacticas_estudiantes", public."users", public."valores_institucionales", public."videos_youtube" RESTART IDENTITY CASCADE;
CREATE TEMP TABLE stage_act_economicas (LIKE public."act_economicas" INCLUDING DEFAULTS);
\copy public."acciones" ("id", "descripcion") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/acciones.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."ejes_transversales" ("id", "descripcion", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/ejes_transversales.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."metodos" ("id", "descripcion", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/metodos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."recursos" ("id", "descripcion", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/recursos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."roles" ("id", "scala", "titulo") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/roles.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."sectores" ("id", "descripcion", "titulo", "imagen_portada_url") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/sectores.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."tecnicas" ("id", "descripcion", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/tecnicas.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."tipo_carreras" ("id", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/tipo_carreras.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."turnos" ("id", "estado", "fecha_actualizacion", "fecha_creacion", "hora_fin", "hora_inicio", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/turnos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."valores_institucionales" ("id", "descripcion", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/valores_institucionales.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."videos_youtube" ("id", "url") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/videos_youtube.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."publicaciones" ("id", "contenido_1", "contenido_2", "descripcion_corta", "destacado", "fecha_evento_fin", "fecha_evento_inicio", "fecha_publicacion", "slug", "tipo", "titulo", "ubicacion") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/publicaciones.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."posts" ("id", "comentarios_activos", "contenido", "creado_por_uid", "entidad_id", "entidad_tipo", "estado", "fecha_actualizacion", "fecha_creacion", "fecha_publicacion", "imagen_portada_url", "resumen", "slug", "tipo", "titulo") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/posts.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."dato_general" ("id", "correo", "direccion", "facebook", "instagram", "nombre_institucion", "pagina_web", "rd", "ruc", "telefono_1", "telefono_2", "tiktok", "twitter", "youtube") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/dato_general.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."anios" ("id", "nombre", "titulo") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/anios.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."horarios" ("id", "activo", "descripcion", "dias_semana", "fecha_actualizacion", "fecha_creacion", "nombre", "regla", "viernes_alterno_inicio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/horarios.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."paquetes" ("id", "archivado", "descripcion", "titulo") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/paquetes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."users" ("id", "apellido_materno", "apellido_paterno", "apellidos", "avatar", "blocked", "celular", "confirmed", "direccion", "distrito", "dni", "document_id", "email", "estado_civil", "fecha_nacimiento", "instruccion", "nombre", "provider", "sexo", "telefono", "tipo_documento", "username", "rol_id", "email_creador", "fecha_creacion", "fecha_modificacion", "correo_institucional", "dni_imagen_frente_url", "dni_imagen_reverso_url", "nacionalidad", "dni_imagen_frente_procesada_url", "dni_imagen_reverso_procesada_url", "fecha_vencimiento") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/users.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."familias" ("id", "sector_id", "descripcion", "titulo", "imagen_portada_url") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/familias.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy stage_act_economicas ("id", "especialidad_id", "familia_id", "descripcion", "titulo", "imagen_portada_url") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/act_economicas.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
INSERT INTO public."act_economicas" ("id", "especialidad_id", "familia_id", "descripcion", "titulo", "imagen_portada_url") SELECT "id", NULL, "familia_id", "descripcion", "titulo", "imagen_portada_url" FROM stage_act_economicas;
\copy public."especialidades" ("id", "act_economica_id", "descripcion", "descripcion_2", "slug", "titulo", "titulo_comercial", "imagen_portada_url") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/especialidades.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
UPDATE public."act_economicas" a SET "especialidad_id" = s."especialidad_id" FROM stage_act_economicas s WHERE a."id" = s."id" AND s."especialidad_id" IS NOT NULL;
\copy public."carreras" ("id", "nombre", "codigo", "descripcion", "creado_en", "actualizado_en", "act_economica_id", "imagen_portada_url", "tipo_carrera_id", "nivel", "creditos", "descripcion_2", "duracion", "slug", "titulo", "titulo_comercial") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/carreras.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."personales" ("id", "user_id", "display_name", "memo") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/personales.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."personal_especialidades" ("personal_id", "especialidad_id", "id", "orden") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/personal_especialidades.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."semestres" ("id", "coordinador_1_id", "coordinador_2_id", "director_id", "archivado", "descripcion", "titulo", "anio_id", "fin", "inicio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/semestres.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."planes" ("id", "creditos", "descripcion_2", "duracion", "slug", "titulo_comercial", "carrera_id", "imagen_portada_url", "anio", "genera", "nro", "periodo_caducidad", "resolucion_tipo", "periodo_vigencia_id", "plan_estudio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/planes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."modulos" ("id", "activo", "creditos", "descripcion", "horas", "metas", "orden", "slug", "titulo", "titulo_comercial", "plan_id", "carrera_id", "descripcion_2") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/modulos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."unidades_didacticas" ("id", "modulo_id", "creditos", "duracion", "nombre", "sigla") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/unidades_didacticas.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."capacidades_terminales" ("id", "unidad_didactica_id", "descripcion", "sigla") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/capacidades_terminales.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."indicadores_capacidad" ("id", "capacidad_terminal_id", "descripcion", "sigla") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/indicadores_capacidad.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."aprendizajes" ("id", "indicador_capacidad_id", "descripcion", "sigla") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/aprendizajes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."actividades" ("id", "aprendizaje_id", "eje_transversal_id", "valor_institucional_id", "ambiente", "bibliografia", "descripcion", "duracion", "fecha", "nombre", "proposito") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/actividades.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."evaluaciones" ("id", "actividad_id", "indicador_capacidad_id", "metodo_id", "tecnica_id", "instrumento") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/evaluaciones.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."aspectos_evaluacion" ("id", "evaluacion_id", "descripcion") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/aspectos_evaluacion.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."fases" ("id", "accion_id", "actividad_id", "descripcion", "duracion", "metodologia", "nombre") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/fases.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."fases_metodos" ("id", "fase_id", "metodo_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/fases_metodos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."fases_recursos" ("id", "fase_id", "recurso_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/fases_recursos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."fases_tecnicas" ("id", "fase_id", "tecnica_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/fases_tecnicas.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."calendarios" ("id", "descripcion", "titulo", "activo", "color", "fecha_actualizacion", "fecha_creacion", "anio_id", "semestre_id", "fin", "inicio", "horario_id", "duracion", "archivado", "fecha_fin", "fecha_ini", "tipo") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/calendarios.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."grupos" ("id", "personal_id", "archivado", "descripcion", "nombre_display", "turno", "paquete_id", "grupo_ord", "semestre_id", "turno_id", "estado", "fecha_actualizacion", "fecha_creacion", "horario_id", "calendario_id", "modulo_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/grupos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."eventos" ("id", "calendario_id", "color", "descripcion", "estado", "fecha_actualizacion", "fecha_creacion", "fecha_fin", "fecha_inicio", "tipo_evento", "titulo", "todo_el_dia", "ubicacion", "semestre_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/eventos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."evento_recurrencias" ("id", "evento_id", "activo", "cantidad_ocurrencias", "dia_mes", "dias_semana", "fecha_actualizacion", "fecha_creacion", "fecha_fin", "fecha_inicio", "frecuencia", "intervalo", "regla_especial", "semana_mes", "horario_id", "turno_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/evento_recurrencias.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."evento_ocurrencias" ("id", "evento_id", "grupo_id", "recurrencia_id", "estado", "fecha_actualizacion", "fecha_creacion", "fecha_fin", "fecha_inicio", "numero_ocurrencia", "observacion", "tipo_ocurrencia") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/evento_ocurrencias.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."evento_relaciones" ("id", "evento_id", "entidad_id", "entidad_tipo", "fecha_actualizacion", "fecha_creacion") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/evento_relaciones.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."recordatorios" ("id", "evento_id", "evento_ocurrencia_id", "enviado", "fecha_actualizacion", "fecha_creacion", "fecha_envio", "medio", "minutos_antes", "tipo_recordatorio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/recordatorios.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."matriculas" ("id", "archivado", "fecha", "recibo", "paquete_id", "user_id", "semestre_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/matriculas.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."modulo_videos" ("id", "modulo_id", "video_id", "field", "orden") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/modulo_videos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."publicacion_videos" ("id", "publicacion_id", "video_id", "field", "orden") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/publicacion_videos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."paquete_modulos" ("id", "modulo_id", "paquete_id", "obligatorio", "orden") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/paquete_modulos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."paquete_grupos" ("paquete_id", "grupo_id", "grupo_ord", "id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/paquete_grupos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."grupo_modulos" ("id", "grupo_id", "modulo_id", "obligatorio", "orden", "calendario_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/grupo_modulos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."matricula_users" ("matricula_id", "user_id", "id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/matricula_users.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."matricula_grupos" ("matricula_id", "grupo_id", "id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/matricula_grupos.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."matricula_paquetes" ("matricula_id", "paquete_id", "id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/matricula_paquetes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."modulos_estudiantes" ("id", "matricula_id", "modulo_id", "promedio", "grupo_id") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/modulos_estudiantes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."unidades_didacticas_estudiantes" ("id", "matricula_id", "unidad_didactica_id", "promedio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/unidades_didacticas_estudiantes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."capacidades_terminales_estudiantes" ("id", "capacidad_terminal_id", "matricula_id", "promedio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/capacidades_terminales_estudiantes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."indicadores_capacidad_estudiantes" ("id", "indicador_capacidad_id", "matricula_id", "promedio") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/indicadores_capacidad_estudiantes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."evaluaciones_estudiantes" ("id", "evaluacion_id", "matricula_id", "nota") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/evaluaciones_estudiantes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."aspectos_evaluacion_estudiantes" ("id", "aspecto_evaluacion_id", "evaluacion_estudiante_id", "puntaje") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/aspectos_evaluacion_estudiantes.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
\copy public."asistencias" ("id", "evento_ocurrencia_id", "matricula_id", "registrado_por_id", "estado_asistencia", "fecha_actualizacion", "fecha_creacion", "observacion", "registrado_at") FROM 'D:/_Desarrollo/cetprosmp-next/backups/20260702-152346/local/dataconnect_csv/asistencias.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8')
SELECT setval(pg_get_serial_sequence('public."acciones"','id'), COALESCE((SELECT MAX("id") FROM public."acciones"), 1), (SELECT MAX("id") IS NOT NULL FROM public."acciones"));
SELECT setval(pg_get_serial_sequence('public."act_economicas"','id'), COALESCE((SELECT MAX("id") FROM public."act_economicas"), 1), (SELECT MAX("id") IS NOT NULL FROM public."act_economicas"));
SELECT setval(pg_get_serial_sequence('public."actividades"','id'), COALESCE((SELECT MAX("id") FROM public."actividades"), 1), (SELECT MAX("id") IS NOT NULL FROM public."actividades"));
SELECT setval(pg_get_serial_sequence('public."anios"','id'), COALESCE((SELECT MAX("id") FROM public."anios"), 1), (SELECT MAX("id") IS NOT NULL FROM public."anios"));
SELECT setval(pg_get_serial_sequence('public."aprendizajes"','id'), COALESCE((SELECT MAX("id") FROM public."aprendizajes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."aprendizajes"));
SELECT setval(pg_get_serial_sequence('public."asistencias"','id'), COALESCE((SELECT MAX("id") FROM public."asistencias"), 1), (SELECT MAX("id") IS NOT NULL FROM public."asistencias"));
SELECT setval(pg_get_serial_sequence('public."aspectos_evaluacion"','id'), COALESCE((SELECT MAX("id") FROM public."aspectos_evaluacion"), 1), (SELECT MAX("id") IS NOT NULL FROM public."aspectos_evaluacion"));
SELECT setval(pg_get_serial_sequence('public."aspectos_evaluacion_estudiantes"','id'), COALESCE((SELECT MAX("id") FROM public."aspectos_evaluacion_estudiantes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."aspectos_evaluacion_estudiantes"));
SELECT setval(pg_get_serial_sequence('public."calendarios"','id'), COALESCE((SELECT MAX("id") FROM public."calendarios"), 1), (SELECT MAX("id") IS NOT NULL FROM public."calendarios"));
SELECT setval(pg_get_serial_sequence('public."capacidades_terminales"','id'), COALESCE((SELECT MAX("id") FROM public."capacidades_terminales"), 1), (SELECT MAX("id") IS NOT NULL FROM public."capacidades_terminales"));
SELECT setval(pg_get_serial_sequence('public."capacidades_terminales_estudiantes"','id'), COALESCE((SELECT MAX("id") FROM public."capacidades_terminales_estudiantes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."capacidades_terminales_estudiantes"));
SELECT setval(pg_get_serial_sequence('public."carreras"','id'), COALESCE((SELECT MAX("id") FROM public."carreras"), 1), (SELECT MAX("id") IS NOT NULL FROM public."carreras"));
SELECT setval(pg_get_serial_sequence('public."dato_general"','id'), COALESCE((SELECT MAX("id") FROM public."dato_general"), 1), (SELECT MAX("id") IS NOT NULL FROM public."dato_general"));
SELECT setval(pg_get_serial_sequence('public."ejes_transversales"','id'), COALESCE((SELECT MAX("id") FROM public."ejes_transversales"), 1), (SELECT MAX("id") IS NOT NULL FROM public."ejes_transversales"));
SELECT setval(pg_get_serial_sequence('public."especialidades"','id'), COALESCE((SELECT MAX("id") FROM public."especialidades"), 1), (SELECT MAX("id") IS NOT NULL FROM public."especialidades"));
SELECT setval(pg_get_serial_sequence('public."evaluaciones"','id'), COALESCE((SELECT MAX("id") FROM public."evaluaciones"), 1), (SELECT MAX("id") IS NOT NULL FROM public."evaluaciones"));
SELECT setval(pg_get_serial_sequence('public."evaluaciones_estudiantes"','id'), COALESCE((SELECT MAX("id") FROM public."evaluaciones_estudiantes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."evaluaciones_estudiantes"));
SELECT setval(pg_get_serial_sequence('public."evento_ocurrencias"','id'), COALESCE((SELECT MAX("id") FROM public."evento_ocurrencias"), 1), (SELECT MAX("id") IS NOT NULL FROM public."evento_ocurrencias"));
SELECT setval(pg_get_serial_sequence('public."evento_recurrencias"','id'), COALESCE((SELECT MAX("id") FROM public."evento_recurrencias"), 1), (SELECT MAX("id") IS NOT NULL FROM public."evento_recurrencias"));
SELECT setval(pg_get_serial_sequence('public."evento_relaciones"','id'), COALESCE((SELECT MAX("id") FROM public."evento_relaciones"), 1), (SELECT MAX("id") IS NOT NULL FROM public."evento_relaciones"));
SELECT setval(pg_get_serial_sequence('public."eventos"','id'), COALESCE((SELECT MAX("id") FROM public."eventos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."eventos"));
SELECT setval(pg_get_serial_sequence('public."familias"','id'), COALESCE((SELECT MAX("id") FROM public."familias"), 1), (SELECT MAX("id") IS NOT NULL FROM public."familias"));
SELECT setval(pg_get_serial_sequence('public."fases"','id'), COALESCE((SELECT MAX("id") FROM public."fases"), 1), (SELECT MAX("id") IS NOT NULL FROM public."fases"));
SELECT setval(pg_get_serial_sequence('public."fases_metodos"','id'), COALESCE((SELECT MAX("id") FROM public."fases_metodos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."fases_metodos"));
SELECT setval(pg_get_serial_sequence('public."fases_recursos"','id'), COALESCE((SELECT MAX("id") FROM public."fases_recursos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."fases_recursos"));
SELECT setval(pg_get_serial_sequence('public."fases_tecnicas"','id'), COALESCE((SELECT MAX("id") FROM public."fases_tecnicas"), 1), (SELECT MAX("id") IS NOT NULL FROM public."fases_tecnicas"));
SELECT setval(pg_get_serial_sequence('public."grupo_modulos"','id'), COALESCE((SELECT MAX("id") FROM public."grupo_modulos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."grupo_modulos"));
SELECT setval(pg_get_serial_sequence('public."grupos"','id'), COALESCE((SELECT MAX("id") FROM public."grupos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."grupos"));
SELECT setval(pg_get_serial_sequence('public."horarios"','id'), COALESCE((SELECT MAX("id") FROM public."horarios"), 1), (SELECT MAX("id") IS NOT NULL FROM public."horarios"));
SELECT setval(pg_get_serial_sequence('public."indicadores_capacidad"','id'), COALESCE((SELECT MAX("id") FROM public."indicadores_capacidad"), 1), (SELECT MAX("id") IS NOT NULL FROM public."indicadores_capacidad"));
SELECT setval(pg_get_serial_sequence('public."indicadores_capacidad_estudiantes"','id'), COALESCE((SELECT MAX("id") FROM public."indicadores_capacidad_estudiantes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."indicadores_capacidad_estudiantes"));
SELECT setval(pg_get_serial_sequence('public."matricula_grupos"','id'), COALESCE((SELECT MAX("id") FROM public."matricula_grupos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."matricula_grupos"));
SELECT setval(pg_get_serial_sequence('public."matricula_paquetes"','id'), COALESCE((SELECT MAX("id") FROM public."matricula_paquetes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."matricula_paquetes"));
SELECT setval(pg_get_serial_sequence('public."matricula_users"','id'), COALESCE((SELECT MAX("id") FROM public."matricula_users"), 1), (SELECT MAX("id") IS NOT NULL FROM public."matricula_users"));
SELECT setval(pg_get_serial_sequence('public."matriculas"','id'), COALESCE((SELECT MAX("id") FROM public."matriculas"), 1), (SELECT MAX("id") IS NOT NULL FROM public."matriculas"));
SELECT setval(pg_get_serial_sequence('public."metodos"','id'), COALESCE((SELECT MAX("id") FROM public."metodos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."metodos"));
SELECT setval(pg_get_serial_sequence('public."modulo_videos"','id'), COALESCE((SELECT MAX("id") FROM public."modulo_videos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."modulo_videos"));
SELECT setval(pg_get_serial_sequence('public."modulos"','id'), COALESCE((SELECT MAX("id") FROM public."modulos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."modulos"));
SELECT setval(pg_get_serial_sequence('public."modulos_estudiantes"','id'), COALESCE((SELECT MAX("id") FROM public."modulos_estudiantes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."modulos_estudiantes"));
SELECT setval(pg_get_serial_sequence('public."paquete_grupos"','id'), COALESCE((SELECT MAX("id") FROM public."paquete_grupos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."paquete_grupos"));
SELECT setval(pg_get_serial_sequence('public."paquete_modulos"','id'), COALESCE((SELECT MAX("id") FROM public."paquete_modulos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."paquete_modulos"));
SELECT setval(pg_get_serial_sequence('public."paquetes"','id'), COALESCE((SELECT MAX("id") FROM public."paquetes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."paquetes"));
SELECT setval(pg_get_serial_sequence('public."personal_especialidades"','id'), COALESCE((SELECT MAX("id") FROM public."personal_especialidades"), 1), (SELECT MAX("id") IS NOT NULL FROM public."personal_especialidades"));
SELECT setval(pg_get_serial_sequence('public."personales"','id'), COALESCE((SELECT MAX("id") FROM public."personales"), 1), (SELECT MAX("id") IS NOT NULL FROM public."personales"));
SELECT setval(pg_get_serial_sequence('public."planes"','id'), COALESCE((SELECT MAX("id") FROM public."planes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."planes"));
SELECT setval(pg_get_serial_sequence('public."posts"','id'), COALESCE((SELECT MAX("id") FROM public."posts"), 1), (SELECT MAX("id") IS NOT NULL FROM public."posts"));
SELECT setval(pg_get_serial_sequence('public."publicacion_videos"','id'), COALESCE((SELECT MAX("id") FROM public."publicacion_videos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."publicacion_videos"));
SELECT setval(pg_get_serial_sequence('public."publicaciones"','id'), COALESCE((SELECT MAX("id") FROM public."publicaciones"), 1), (SELECT MAX("id") IS NOT NULL FROM public."publicaciones"));
SELECT setval(pg_get_serial_sequence('public."recordatorios"','id'), COALESCE((SELECT MAX("id") FROM public."recordatorios"), 1), (SELECT MAX("id") IS NOT NULL FROM public."recordatorios"));
SELECT setval(pg_get_serial_sequence('public."recursos"','id'), COALESCE((SELECT MAX("id") FROM public."recursos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."recursos"));
SELECT setval(pg_get_serial_sequence('public."roles"','id'), COALESCE((SELECT MAX("id") FROM public."roles"), 1), (SELECT MAX("id") IS NOT NULL FROM public."roles"));
SELECT setval(pg_get_serial_sequence('public."sectores"','id'), COALESCE((SELECT MAX("id") FROM public."sectores"), 1), (SELECT MAX("id") IS NOT NULL FROM public."sectores"));
SELECT setval(pg_get_serial_sequence('public."semestres"','id'), COALESCE((SELECT MAX("id") FROM public."semestres"), 1), (SELECT MAX("id") IS NOT NULL FROM public."semestres"));
SELECT setval(pg_get_serial_sequence('public."tecnicas"','id'), COALESCE((SELECT MAX("id") FROM public."tecnicas"), 1), (SELECT MAX("id") IS NOT NULL FROM public."tecnicas"));
SELECT setval(pg_get_serial_sequence('public."tipo_carreras"','id'), COALESCE((SELECT MAX("id") FROM public."tipo_carreras"), 1), (SELECT MAX("id") IS NOT NULL FROM public."tipo_carreras"));
SELECT setval(pg_get_serial_sequence('public."turnos"','id'), COALESCE((SELECT MAX("id") FROM public."turnos"), 1), (SELECT MAX("id") IS NOT NULL FROM public."turnos"));
SELECT setval(pg_get_serial_sequence('public."unidades_didacticas"','id'), COALESCE((SELECT MAX("id") FROM public."unidades_didacticas"), 1), (SELECT MAX("id") IS NOT NULL FROM public."unidades_didacticas"));
SELECT setval(pg_get_serial_sequence('public."unidades_didacticas_estudiantes"','id'), COALESCE((SELECT MAX("id") FROM public."unidades_didacticas_estudiantes"), 1), (SELECT MAX("id") IS NOT NULL FROM public."unidades_didacticas_estudiantes"));
SELECT setval(pg_get_serial_sequence('public."users"','id'), COALESCE((SELECT MAX("id") FROM public."users"), 1), (SELECT MAX("id") IS NOT NULL FROM public."users"));
SELECT setval(pg_get_serial_sequence('public."valores_institucionales"','id'), COALESCE((SELECT MAX("id") FROM public."valores_institucionales"), 1), (SELECT MAX("id") IS NOT NULL FROM public."valores_institucionales"));
SELECT setval(pg_get_serial_sequence('public."videos_youtube"','id'), COALESCE((SELECT MAX("id") FROM public."videos_youtube"), 1), (SELECT MAX("id") IS NOT NULL FROM public."videos_youtube"));
ROLLBACK;
