'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Box,Button,CircularProgress,LinearProgress,MenuItem,Paper,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,Typography} from '@mui/material';
import PrintIcon from '@mui/icons-material/Print';
import DownloadIcon from '@mui/icons-material/Download';
import {httpsCallable} from 'firebase/functions';
import {functions} from '@/lib/firebase';
import {useIntranetPermissions} from '@/hooks/useIntranetPermissions';
import {dayInLima} from '@/lib/calendar';
import {activityLabel,unitLabel,parteGroupLabel,ParteDiarioRow} from '@/lib/parteDiario';
import AutoDismissAlert from '@/components/intranet/AutoDismissAlert';
import ParteDiarioModal from '@/components/parte-diario/ParteDiarioModal';
import type {ParteReportData,ParteMetrics,InformeRow} from '../../../../../../functions/src/modules/parte-diario/reportAnalytics';
import type {ValuationField} from '../../../../../../functions/src/modules/parte-diario/valuations';

type Filters={desde:string;hasta:string;semestreId:number|'';familiaId:number|'';docenteId:number|''};
const ratingTitles:Record<ValuationField,string>={silabo:'Sílabo',fichaActividad:'Ficha de Actividad',instrumentoEvaluacion:'Instrumento de Evaluación',material:'Materiales',tareas:'Tareas'};
const number=(value:number|null,suffix='')=>value==null?'Sin datos':new Intl.NumberFormat('es-PE',{maximumFractionDigits:1}).format(value)+suffix;
const percent=(value:number|null)=>number(value,'%');
function overview(m:ParteMetrics){return m.registros?`Se registraron ${m.registros} partes para ${m.programadas} sesiones o jornadas programadas. Cobertura de registros: ${percent(m.cobertura)}. Asistencia registrada: ${percent(m.asistencia)}, en ${m.jornadasConAsistencia} jornadas. Actividades registradas frente a las programadas en el período: ${m.actividadesRegistradas} de ${m.actividadesProgramadas} (${percent(m.avance)}). Valoración media declarada: ${number(m.indice)} de 4.`:'No hay partes registrados para este período y estos filtros. No se pueden valorar el rendimiento, la asistencia ni la calidad sin registros.';}
function recommendations(m:ParteMetrics){if(!m.registros)return 'Completar los partes diarios del período para contar con evidencias de seguimiento.';return [m.cobertura!=null&&m.cobertura<100?'Completar los registros de las sesiones y jornadas que aún no tienen parte.':'',m.jornadasSinAsistencia?'Completar los asistentes en los registros que tienen este campo vacío.':'',m.inasistenciasAcumuladas>0?'Revisar las inasistencias registradas y acordar acciones de acompañamiento.':'',m.valoraciones.instrumentoEvaluacion.distribucion.slice(0,3).some(n=>n>0)?'Revisar los instrumentos registrados como inexistentes, no aplicados o en proceso.':'',m.valoraciones.tareas.distribucion[2]?'Revisar las tareas publicadas que aún no tienen respuestas y el seguimiento al estudiante.':'',m.valoraciones.material.distribucion.slice(0,3).some(n=>n>0)?'Revisar los materiales registrados como inexistentes o no publicados.':''].filter(Boolean).join('\n')||'Mantener el seguimiento de las actividades, la asistencia y las valoraciones documentadas.';}
export default function ParteDiarioReportPage(){
 const {can,loading:permissionLoading}=useIntranetPermissions(),today=dayInLima(new Date());
 const [filters,setFilters]=useState<Filters>({desde:today.slice(0,7)+'-01',hasta:today,semestreId:'',familiaId:'',docenteId:''}),[scope,setScope]=useState<Filters|null>(null),[data,setData]=useState<ParteReportData|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [editor,setEditor]=useState({id:null as number|null,titulo:'',analisis:'',recomendaciones:'',version:null as string|null}),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[selected,setSelected]=useState<{fecha:string;row:ParteDiarioRow}|null>(null);
 const request=useRef(0),mounted=useRef(false);
 const load=useCallback(async(next:Filters,offset=0,resetEditor=true)=>{const req=++request.current;setLoading(true);setError('');try{const result=await httpsCallable<unknown,ParteReportData>(functions,'getParteReporte')({...next,offset});if(req!==request.current)return;setData(result.data);setScope(next);if(resetEditor){const old=result.data.informes[0];setEditor(old?{id:old.id,titulo:old.titulo,analisis:old.analisis,recomendaciones:old.recomendaciones,version:old.fechaActualizacion}:{id:null,titulo:next.docenteId?'Informe individual del docente':next.familiaId?'Informe de la familia':'Informe general por familias',analisis:overview(result.data.total),recomendaciones:recommendations(result.data.total),version:null});setDirty(false);}}catch(err){if(req===request.current)setError(err instanceof Error?err.message:'No se pudo cargar el reporte.');}finally{if(req===request.current)setLoading(false);}},[]);
 useEffect(()=>{if(!permissionLoading&&can('reportes-parte-diario','view')&&!mounted.current){mounted.current=true;void load(filters);}},[permissionLoading,can,filters,load]);
 const apply=(next:Filters)=>{if(dirty&&!window.confirm('Cambiar los filtros descartará la edición del informe que aún no guardaste. ¿Continuar?'))return;setFilters(next);void load(next);};
 const editNote=(note?:InformeRow)=>{if(!data)return;if(dirty&&!window.confirm('¿Descartar la edición actual del informe?'))return;setEditor(note?{id:note.id,titulo:note.titulo,analisis:note.analisis,recomendaciones:note.recomendaciones,version:note.fechaActualizacion}:{id:null,titulo:scope?.docenteId?'Informe individual del docente':scope?.familiaId?'Informe de la familia':'Informe general por familias',analisis:overview(data.total),recomendaciones:recommendations(data.total),version:null});setDirty(false);};
 const save=async()=>{if(!scope)return;setSaving(true);setError('');try{await httpsCallable<unknown,{id:number}>(functions,'saveParteInforme')({...scope,...editor});await load(scope,0,true);setNotice('Informe guardado.');}catch(err){setError(err instanceof Error?err.message:'No se pudo guardar el informe.');}finally{setSaving(false);}};
 const openRecord=async(recordId:number)=>{setError('');try{const result=await httpsCallable<unknown,{fecha:string;row:ParteDiarioRow}>(functions,'getParteReporteRegistro')({id:recordId});setSelected(result.data);}catch(err){setError(err instanceof Error?err.message:'No se pudo abrir el registro.');}};
 const download=()=>{if(!data)return;const rows=[['Tipo','Nombre','Partes','Programadas','Cobertura %','Asistencia %','Actividades registradas','Actividades programadas','Avance %',...Object.values(ratingTitles),'Valoración media (0 a 4)'],...([{type:'General',nombre:'Total',...data.total},...data.porFamilia.map(r=>({type:'Familia',...r})),...data.porDocente.map(r=>({type:'Docente',...r}))]).map(r=>[r.type,r.nombre,r.registros,r.programadas,r.cobertura??'',r.asistencia??'',r.actividadesRegistradas,r.actividadesProgramadas,r.avance??'',...Object.keys(ratingTitles).map(f=>r.valoraciones[f as ValuationField].promedio??''),r.indice??''])];const quote=(v:unknown)=>{let s=String(v);if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const blob=new Blob(['\ufeff'+rows.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`parte-diario_${data.desde}_${data.hasta}.csv`;link.click();URL.revokeObjectURL(url);};
 const summaryTable=(dimension:'familia'|'docente')=>{if(!data)return null;const rows=dimension==='familia'?data.porFamilia:data.porDocente;return <Paper sx={{p:2,mb:2}}><Typography variant="h6" sx={{mb:1}}>{dimension==='familia'?'Informe general por familia':'Rendimiento registrado por docente'}</Typography><TableContainer><Table size="small" aria-label={dimension==='familia'?'Estadísticas por familia':'Estadísticas por docente'}><TableHead><TableRow>{[dimension==='familia'?'Familia':'Docente','Partes / programadas','Cobertura','Asistencia','Avance de actividades','Valoración media / 4'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.id}><TableCell><Button sx={{textAlign:'left',justifyContent:'flex-start',textTransform:'none'}} onClick={()=>apply({...filters,semestreId:scope?.semestreId??'',familiaId:dimension==='familia'&&r.id?r.id:scope?.familiaId??'',docenteId:dimension==='docente'?r.id:''})} disabled={loading||saving}>{r.nombre}</Button></TableCell><TableCell>{r.registros} / {r.programadas}</TableCell><TableCell>{percent(r.cobertura)}</TableCell><TableCell>{percent(r.asistencia)}</TableCell><TableCell>{r.actividadesRegistradas} / {r.actividadesProgramadas} ({percent(r.avance)})</TableCell><TableCell>{number(r.indice)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Paper>;};
 if(permissionLoading)return <CircularProgress aria-label="Cargando permisos"/>;
 if(!can('reportes-parte-diario','view'))return <AutoDismissAlert severity="info">No tienes permiso para ver el reporte Parte diario.</AutoDismissAlert>;
 const total=data?.total,share=(field:ValuationField,values:number[])=>{if(!total?.valoraciones[field].cantidad)return null;return values.reduce((n,v)=>n+total.valoraciones[field].distribucion[v],0)/total.valoraciones[field].cantidad*100;};
 return <Box sx={{p:2}}>
  <style>{`@media print{body *{visibility:hidden}#parte-report-print,#parte-report-print *{visibility:visible}#parte-report-print{position:absolute;left:0;top:0;width:100%}.no-print{display:none!important}.print-only{display:block!important}#parte-report-print table{break-inside:auto}#parte-report-print tr{break-inside:avoid}}.print-only{display:none}`}</style>
  <Stack className="no-print" direction="row" alignItems="center" gap={2} sx={{mb:2}}><Typography component="h1" variant="h5" sx={{flex:1}}>Parte diario</Typography><Button startIcon={<DownloadIcon/>} onClick={download} disabled={!data||loading}>CSV</Button><Button startIcon={<PrintIcon/>} onClick={()=>window.print()} disabled={!data||loading}>Imprimir / PDF</Button></Stack>
  <Paper className="no-print" sx={{p:2,mb:2}}><Stack direction="row" gap={2} flexWrap="wrap">
   <TextField type="date" label="Desde" value={filters.desde} slotProps={{inputLabel:{shrink:true},htmlInput:{max:today}}} onChange={e=>setFilters({...filters,desde:e.target.value})}/><TextField type="date" label="Hasta" value={filters.hasta} slotProps={{inputLabel:{shrink:true},htmlInput:{max:today}}} onChange={e=>setFilters({...filters,hasta:e.target.value})}/>
   <TextField select label="Semestre" value={filters.semestreId} sx={{minWidth:150}} onChange={e=>{const id=e.target.value===''?'':Number(e.target.value),sem=data?.opciones.semestres.find(s=>s.id===id);setFilters({...filters,semestreId:id,desde:sem?.inicio?.slice(0,10)||filters.desde,hasta:sem?.fin?(sem.fin.slice(0,10)<today?sem.fin.slice(0,10):today):filters.hasta});}}><MenuItem value="">Todos</MenuItem>{data?.opciones.semestres.map(s=><MenuItem key={s.id} value={s.id}>{s.titulo}</MenuItem>)}</TextField>
   <TextField select label="Familia" value={filters.familiaId} sx={{minWidth:220,maxWidth:330}} onChange={e=>setFilters({...filters,familiaId:e.target.value===''?'':Number(e.target.value)})}><MenuItem value="">Todas</MenuItem>{data?.opciones.familias.map(f=><MenuItem key={f.id} value={f.id}>{f.titulo}</MenuItem>)}</TextField>
   <TextField select label="Docente" value={filters.docenteId} sx={{minWidth:250}} onChange={e=>setFilters({...filters,docenteId:e.target.value===''?'':Number(e.target.value)})}><MenuItem value="">Todos</MenuItem>{data?.opciones.docentes.map(p=><MenuItem key={p.id} value={p.id}>{p.nombre}</MenuItem>)}</TextField><Button variant="contained" onClick={()=>apply(filters)} disabled={loading||saving}>Aplicar filtros</Button>
  </Stack></Paper>
  {error&&<AutoDismissAlert severity="error" onClose={()=>setError('')}>{error}</AutoDismissAlert>}{notice&&<AutoDismissAlert severity="success" onClose={()=>setNotice('')}>{notice}</AutoDismissAlert>}{loading&&<LinearProgress aria-label="Cargando estadísticas del Parte Diario" sx={{mb:2}}/>}
  {data&&total&&<Box id="parte-report-print">
   <Typography variant="h5" className="print-only">{editor.titulo}</Typography><Typography sx={{mb:2}}>Del {data.desde} al {data.hasta}{scope?.familiaId?` · ${data.opciones.familias.find(f=>f.id===scope.familiaId)?.titulo}`:''}{scope?.docenteId?` · ${data.opciones.docentes.find(p=>p.id===scope.docenteId)?.nombre}`:''}</Typography>
   {!total.registros&&<AutoDismissAlert severity="info">No hay partes registrados para el período y los filtros seleccionados. Los valores sin evidencia se muestran como «Sin datos».</AutoDismissAlert>}
   <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(4,1fr)'},gap:2,mb:2}}>{[['Cobertura de registros',percent(total.cobertura),`${total.registros} partes · ${total.programadas} sesiones/jornadas programadas`],['Asistencia por jornada',percent(total.asistencia),`${total.asistentesAcumulados} asistencias / ${total.matriculadosAcumulados} plazas registradas`],['Avance registrado',percent(total.avance),`${total.actividadesRegistradas} de ${total.actividadesProgramadas} actividades programadas`],['Valoración media',`${number(total.indice)}${total.indice==null?'':' / 4'}`,'Promedio de valoraciones registradas']].map(([label,value,detail])=><Paper key={label} sx={{p:2}}><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{value}</Typography><Typography variant="caption">{detail}</Typography></Paper>)}</Box>
   <Typography variant="body2" color="text.secondary" sx={{mb:2}}>La asistencia se cuenta una vez por grupo y día, usando el último registro con asistentes. Son asistencias acumuladas, no alumnos únicos. Los campos vacíos se excluyen; hay {total.jornadasSinAsistencia} jornadas registradas sin asistencia. El avance compara actividades seleccionadas en los partes con las programadas en el período y no certifica su ejecución completa.</Typography>
   {!!total.asistenciasDiscordantes&&<AutoDismissAlert severity="warning">Hay {total.asistenciasDiscordantes} jornadas con cantidades de asistentes distintas entre sesiones. Se tomó el último registro con asistencia.</AutoDismissAlert>}
   <Paper sx={{p:2,mb:2}}><Typography variant="h6" sx={{mb:2}}>Calidad registrada de documentos, evaluación y materiales</Typography>{(Object.keys(ratingTitles) as ValuationField[]).map(field=>{const rating=total.valoraciones[field];return <Box key={field} sx={{mb:2}}><Stack direction="row" justifyContent="space-between"><Typography>{ratingTitles[field]}</Typography><Typography>{rating.promedio==null?'Sin datos':`${number(rating.promedio)} / 4`} · {rating.cantidad} valoraciones</Typography></Stack><LinearProgress variant="determinate" value={rating.promedio==null?0:rating.promedio*25} sx={{height:10,borderRadius:1,my:0.5}}/><Typography variant="caption">Distribución de valores 0–4: {rating.distribucion.map((n,i)=>`${i}: ${n}`).join(' · ')}</Typography></Box>;})}<Typography variant="body2">Materiales publicados: {percent(share('material',[3,4]))}. Instrumentos aplicados: {percent(share('instrumentoEvaluacion',[2,3,4]))}. Tareas respondidas completamente: {percent(share('tareas',[4]))}; parcialmente: {percent(share('tareas',[3]))}.</Typography><Typography variant="caption" color="text.secondary">Son valoraciones declaradas. La calidad de la retroalimentación y los resultados individuales de aprendizaje no se registran directamente; se muestran la aplicación de instrumentos y la respuesta a tareas.</Typography></Paper>
   {summaryTable('familia')}{summaryTable('docente')}
   <Paper sx={{p:2,mb:2}}><Typography variant="h6" sx={{mb:2}}>Informe y recomendaciones</Typography><Box className="no-print"><Stack gap={2}>
    <Stack direction="row" gap={1}><TextField select label="Informe guardado" value={editor.id??''} sx={{flex:1}} onChange={e=>editNote(data.informes.find(n=>n.id===Number(e.target.value)))}><MenuItem value="">Nuevo informe</MenuItem>{data.informes.map(n=><MenuItem key={n.id} value={n.id}>{n.titulo}</MenuItem>)}</TextField><Button onClick={()=>editNote()} disabled={saving}>Nuevo</Button></Stack>
    <TextField label="Título del informe" value={editor.titulo} disabled={!can('reportes-parte-diario','edit')||saving} slotProps={{htmlInput:{maxLength:200}}} onChange={e=>{setEditor({...editor,titulo:e.target.value});setDirty(true);}}/>
    <TextField label="Análisis" multiline minRows={4} value={editor.analisis} disabled={!can('reportes-parte-diario','edit')||saving} slotProps={{htmlInput:{maxLength:20000}}} onChange={e=>{setEditor({...editor,analisis:e.target.value});setDirty(true);}}/>
    <TextField label="Recomendaciones" multiline minRows={3} value={editor.recomendaciones} disabled={!can('reportes-parte-diario','edit')||saving} slotProps={{htmlInput:{maxLength:20000}}} onChange={e=>{setEditor({...editor,recomendaciones:e.target.value});setDirty(true);}}/>
    {can('reportes-parte-diario','edit')&&<Stack direction="row" gap={2}><Button variant="contained" onClick={()=>void save()} disabled={saving||loading||!editor.titulo.trim()}>Guardar informe</Button><Button onClick={()=>editNote(data.informes.find(n=>n.id===editor.id))} disabled={saving}>Descartar edición</Button></Stack>}
   </Stack></Box><Box className="print-only"><Typography sx={{whiteSpace:'pre-wrap',mb:2}}>{editor.analisis}</Typography><Typography fontWeight={700}>Recomendaciones</Typography><Typography sx={{whiteSpace:'pre-wrap'}}>{editor.recomendaciones}</Typography></Box></Paper>
   <Paper className="no-print" sx={{p:2}}><Typography variant="h6">Registros del Parte Diario</Typography><Typography variant="body2" sx={{mb:1}}>Mostrando {data.registrosTotal?data.offset+1:0}–{data.offset+data.registros.length} de {data.registrosTotal} registros.</Typography><TableContainer><Table size="small" aria-label="Registros del Parte Diario"><TableHead><TableRow>{['Fecha','Docente / grupo-módulo','Unidad','Actividad','Matr.','Asist.',''].map((h,i)=><TableCell key={i}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{data.registros.map(r=><TableRow key={r.id}><TableCell>{r.fecha}</TableCell><TableCell>{r.docente}<Typography variant="caption" display="block">{parteGroupLabel(r.modulo)}</Typography></TableCell><TableCell>{unitLabel(r.unidad)}</TableCell><TableCell>{activityLabel(r.actividad)}</TableCell><TableCell>{r.matriculados}</TableCell><TableCell>{r.asistentes??'Sin registrar'}</TableCell><TableCell><Button onClick={()=>void openRecord(r.id)}>{can('reportes-parte-diario','edit')?'Editar':'Ver'}</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer><Stack direction="row" justifyContent="flex-end" gap={2} sx={{mt:1}}><Button disabled={!data.offset||loading} onClick={()=>scope&&void load(scope,Math.max(0,data.offset-100),false)}>Anterior</Button><Button disabled={data.offset+100>=data.registrosTotal||loading} onClick={()=>scope&&void load(scope,data.offset+100,false)}>Siguiente</Button></Stack></Paper>
  </Box>}
  {selected&&can('reportes-parte-diario','edit')&&<ParteDiarioModal row={selected.row} fecha={selected.fecha} reportRecordId={selected.row.recordId!} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);setNotice('Registro actualizado.');if(scope)void load(scope,data?.offset||0,!dirty);}}/>}
 </Box>;
}
