extend type Query {
  """
  ✨ Look up a single `Accion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  accion(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Accion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Accion_FirstRow
  ): Accion @fdc_generated(from: "Accion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ActEconomica` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  actEconomica(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: ActEconomica_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ActEconomica_FirstRow
  ): ActEconomica @fdc_generated(from: "ActEconomica", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Actividad` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  actividad(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Actividad_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Actividad_FirstRow
  ): Actividad @fdc_generated(from: "Actividad", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Aprendizaje` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  aprendizaje(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Aprendizaje_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Aprendizaje_FirstRow
  ): Aprendizaje @fdc_generated(from: "Aprendizaje", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Asistencia` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  asistencia(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Asistencia_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Asistencia_FirstRow
  ): Asistencia @fdc_generated(from: "Asistencia", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AspectoEvaluacion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  aspectoEvaluacion(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: AspectoEvaluacion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AspectoEvaluacion_FirstRow
  ): AspectoEvaluacion @fdc_generated(from: "AspectoEvaluacion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `AspectoEvaluacionEstudiante` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  aspectoEvaluacionEstudiante(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: AspectoEvaluacionEstudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AspectoEvaluacionEstudiante_FirstRow
  ): AspectoEvaluacionEstudiante @fdc_generated(from: "AspectoEvaluacionEstudiante", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Calendario` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  calendario(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Calendario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Calendario_FirstRow
  ): Calendario @fdc_generated(from: "Calendario", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `CapacidadTerminal` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  capacidadTerminal(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: CapacidadTerminal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CapacidadTerminal_FirstRow
  ): CapacidadTerminal @fdc_generated(from: "CapacidadTerminal", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `CapacidadTerminalEstudiante` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  capacidadTerminalEstudiante(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: CapacidadTerminalEstudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CapacidadTerminalEstudiante_FirstRow
  ): CapacidadTerminalEstudiante @fdc_generated(from: "CapacidadTerminalEstudiante", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Carrera` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  carrera(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Carrera_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Carrera_FirstRow
  ): Carrera @fdc_generated(from: "Carrera", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DatoGeneral` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  datoGeneral(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: DatoGeneral_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DatoGeneral_FirstRow
  ): DatoGeneral @fdc_generated(from: "DatoGeneral", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `EjeTransversal` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  ejeTransversal(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: EjeTransversal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EjeTransversal_FirstRow
  ): EjeTransversal @fdc_generated(from: "EjeTransversal", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Especialidad` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  especialidad(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Especialidad_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Especialidad_FirstRow
  ): Especialidad @fdc_generated(from: "Especialidad", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Evaluacion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  evaluacion(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Evaluacion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Evaluacion_FirstRow
  ): Evaluacion @fdc_generated(from: "Evaluacion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `EvaluacionEstudiante` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  evaluacionEstudiante(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: EvaluacionEstudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EvaluacionEstudiante_FirstRow
  ): EvaluacionEstudiante @fdc_generated(from: "EvaluacionEstudiante", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Evento` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  evento(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Evento_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Evento_FirstRow
  ): Evento @fdc_generated(from: "Evento", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `EventoOcurrencia` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  eventoOcurrencia(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: EventoOcurrencia_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EventoOcurrencia_FirstRow
  ): EventoOcurrencia @fdc_generated(from: "EventoOcurrencia", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `EventoRecurrencia` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  eventoRecurrencia(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: EventoRecurrencia_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EventoRecurrencia_FirstRow
  ): EventoRecurrencia @fdc_generated(from: "EventoRecurrencia", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `EventoRelacion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  eventoRelacion(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: EventoRelacion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: EventoRelacion_FirstRow
  ): EventoRelacion @fdc_generated(from: "EventoRelacion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Familia` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  familia(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Familia_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Familia_FirstRow
  ): Familia @fdc_generated(from: "Familia", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Fase` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  fase(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Fase_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Fase_FirstRow
  ): Fase @fdc_generated(from: "Fase", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FaseMetodo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  faseMetodo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: FaseMetodo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FaseMetodo_FirstRow
  ): FaseMetodo @fdc_generated(from: "FaseMetodo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FaseRecurso` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  faseRecurso(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: FaseRecurso_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FaseRecurso_FirstRow
  ): FaseRecurso @fdc_generated(from: "FaseRecurso", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `FaseTecnica` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  faseTecnica(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: FaseTecnica_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: FaseTecnica_FirstRow
  ): FaseTecnica @fdc_generated(from: "FaseTecnica", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Grupo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  grupo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Grupo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Grupo_FirstRow
  ): Grupo @fdc_generated(from: "Grupo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `IndicadorCapacidad` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  indicadorCapacidad(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: IndicadorCapacidad_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IndicadorCapacidad_FirstRow
  ): IndicadorCapacidad @fdc_generated(from: "IndicadorCapacidad", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `IndicadorCapacidadEstudiante` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  indicadorCapacidadEstudiante(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: IndicadorCapacidadEstudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: IndicadorCapacidadEstudiante_FirstRow
  ): IndicadorCapacidadEstudiante @fdc_generated(from: "IndicadorCapacidadEstudiante", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Matricula` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  matricula(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Matricula_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Matricula_FirstRow
  ): Matricula @fdc_generated(from: "Matricula", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Metodo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  metodo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Metodo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Metodo_FirstRow
  ): Metodo @fdc_generated(from: "Metodo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Modulo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  modulo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Modulo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Modulo_FirstRow
  ): Modulo @fdc_generated(from: "Modulo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ModuloEstudiante` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  moduloEstudiante(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: ModuloEstudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModuloEstudiante_FirstRow
  ): ModuloEstudiante @fdc_generated(from: "ModuloEstudiante", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ModuloVideo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  moduloVideo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: ModuloVideo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModuloVideo_FirstRow
  ): ModuloVideo @fdc_generated(from: "ModuloVideo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Paquete` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  paquete(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Paquete_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Paquete_FirstRow
  ): Paquete @fdc_generated(from: "Paquete", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PaqueteModulo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  paqueteModulo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: PaqueteModulo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PaqueteModulo_FirstRow
  ): PaqueteModulo @fdc_generated(from: "PaqueteModulo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Personal` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  personal(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Personal_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Personal_FirstRow
  ): Personal @fdc_generated(from: "Personal", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PersonalEspecialidad` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  personalEspecialidad(
    """
    The key used to identify the object.
    """
    key: PersonalEspecialidad_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PersonalEspecialidad_FirstRow
  ): PersonalEspecialidad @fdc_generated(from: "PersonalEspecialidad", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Plan` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  plan(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Plan_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Plan_FirstRow
  ): Plan @fdc_generated(from: "Plan", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Post` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  post(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Post_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Post_FirstRow
  ): Post @fdc_generated(from: "Post", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Publicacion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  publicacion(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Publicacion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Publicacion_FirstRow
  ): Publicacion @fdc_generated(from: "Publicacion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `PublicacionVideo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  publicacionVideo(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: PublicacionVideo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PublicacionVideo_FirstRow
  ): PublicacionVideo @fdc_generated(from: "PublicacionVideo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Recordatorio` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  recordatorio(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Recordatorio_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Recordatorio_FirstRow
  ): Recordatorio @fdc_generated(from: "Recordatorio", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Recurso` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  recurso(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Recurso_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Recurso_FirstRow
  ): Recurso @fdc_generated(from: "Recurso", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Rol` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  rol(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Rol_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Rol_FirstRow
  ): Rol @fdc_generated(from: "Rol", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Sector` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  sector(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Sector_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Sector_FirstRow
  ): Sector @fdc_generated(from: "Sector", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Semestre` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  semestre(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Semestre_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Semestre_FirstRow
  ): Semestre @fdc_generated(from: "Semestre", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Tecnica` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tecnica(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Tecnica_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Tecnica_FirstRow
  ): Tecnica @fdc_generated(from: "Tecnica", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `TipoCarrera` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  tipoCarrera(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: TipoCarrera_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TipoCarrera_FirstRow
  ): TipoCarrera @fdc_generated(from: "TipoCarrera", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Turno` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  turno(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: Turno_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Turno_FirstRow
  ): Turno @fdc_generated(from: "Turno", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UnidadDidactica` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  unidadDidactica(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: UnidadDidactica_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UnidadDidactica_FirstRow
  ): UnidadDidactica @fdc_generated(from: "UnidadDidactica", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `UnidadDidacticaEstudiante` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  unidadDidacticaEstudiante(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: UnidadDidacticaEstudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: UnidadDidacticaEstudiante_FirstRow
  ): UnidadDidacticaEstudiante @fdc_generated(from: "UnidadDidacticaEstudiante", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ValorInstitucional` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  valorInstitucional(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: ValorInstitucional_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ValorInstitucional_FirstRow
  ): ValorInstitucional @fdc_generated(from: "ValorInstitucional", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `VideoYoutube` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  videoYoutube(
    """
    The unique ID of the object.
    """
    id: Int

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: Int_Expr

    """
    The key used to identify the object.
    """
    key: VideoYoutube_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoYoutube_FirstRow
  ): VideoYoutube @fdc_generated(from: "VideoYoutube", purpose: QUERY_SINGLE)
  """
  ✨ List `Accion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  accions(
    """
    Filter condition to narrow down the query results.
    """
    where: Accion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Accion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Accion_Having
  ): [Accion!]! @fdc_generated(from: "Accion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ActEconomica` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  actEconomicas(
    """
    Filter condition to narrow down the query results.
    """
    where: ActEconomica_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ActEconomica_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ActEconomica_Having
  ): [ActEconomica!]! @fdc_generated(from: "ActEconomica", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Actividad` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  actividads(
    """
    Filter condition to narrow down the query results.
    """
    where: Actividad_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Actividad_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Actividad_Having
  ): [Actividad!]! @fdc_generated(from: "Actividad", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Aprendizaje` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  aprendizajes(
    """
    Filter condition to narrow down the query results.
    """
    where: Aprendizaje_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Aprendizaje_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Aprendizaje_Having
  ): [Aprendizaje!]! @fdc_generated(from: "Aprendizaje", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Asistencia` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  asistencias(
    """
    Filter condition to narrow down the query results.
    """
    where: Asistencia_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Asistencia_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Asistencia_Having
  ): [Asistencia!]! @fdc_generated(from: "Asistencia", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AspectoEvaluacion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  aspectosEvaluacion(
    """
    Filter condition to narrow down the query results.
    """
    where: AspectoEvaluacion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AspectoEvaluacion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AspectoEvaluacion_Having
  ): [AspectoEvaluacion!]! @fdc_generated(from: "AspectoEvaluacion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `AspectoEvaluacionEstudiante` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  aspectosEvaluacionEstudiantes(
    """
    Filter condition to narrow down the query results.
    """
    where: AspectoEvaluacionEstudiante_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [AspectoEvaluacionEstudiante_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: AspectoEvaluacionEstudiante_Having
  ): [AspectoEvaluacionEstudiante!]! @fdc_generated(from: "AspectoEvaluacionEstudiante", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Calendario` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  calendarios(
    """
    Filter condition to narrow down the query results.
    """
    where: Calendario_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Calendario_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Calendario_Having
  ): [Calendario!]! @fdc_generated(from: "Calendario", purpose: QUERY_MULTIPLE)
  """
  ✨ List `CapacidadTerminal` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  capacidadesTerminales(
    """
    Filter condition to narrow down the query results.
    """
    where: CapacidadTerminal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CapacidadTerminal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CapacidadTerminal_Having
  ): [CapacidadTerminal!]! @fdc_generated(from: "CapacidadTerminal", purpose: QUERY_MULTIPLE)
  """
  ✨ List `CapacidadTerminalEstudiante` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  capacidadesTerminalesEstudiantes(
    """
    Filter condition to narrow down the query results.
    """
    where: CapacidadTerminalEstudiante_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CapacidadTerminalEstudiante_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CapacidadTerminalEstudiante_Having
  ): [CapacidadTerminalEstudiante!]! @fdc_generated(from: "CapacidadTerminalEstudiante", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Carrera` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  carreras(
    """
    Filter condition to narrow down the query results.
    """
    where: Carrera_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Carrera_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Carrera_Having
  ): [Carrera!]! @fdc_generated(from: "Carrera", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DatoGeneral` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  datoGenerals(
    """
    Filter condition to narrow down the query results.
    """
    where: DatoGeneral_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DatoGeneral_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DatoGeneral_Having
  ): [DatoGeneral!]! @fdc_generated(from: "DatoGeneral", purpose: QUERY_MULTIPLE)
  """
  ✨ List `EjeTransversal` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  ejesTransversales(
    """
    Filter condition to narrow down the query results.
    """
    where: EjeTransversal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EjeTransversal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EjeTransversal_Having
  ): [EjeTransversal!]! @fdc_generated(from: "EjeTransversal", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Especialidad` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  especialidads(
    """
    Filter condition to narrow down the query results.
    """
    where: Especialidad_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Especialidad_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Especialidad_Having
  ): [Especialidad!]! @fdc_generated(from: "Especialidad", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Evaluacion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  evaluacions(
    """
    Filter condition to narrow down the query results.
    """
    where: Evaluacion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Evaluacion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Evaluacion_Having
  ): [Evaluacion!]! @fdc_generated(from: "Evaluacion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `EvaluacionEstudiante` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  evaluacionesEstudiantes(
    """
    Filter condition to narrow down the query results.
    """
    where: EvaluacionEstudiante_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EvaluacionEstudiante_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EvaluacionEstudiante_Having
  ): [EvaluacionEstudiante!]! @fdc_generated(from: "EvaluacionEstudiante", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Evento` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  eventos(
    """
    Filter condition to narrow down the query results.
    """
    where: Evento_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Evento_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Evento_Having
  ): [Evento!]! @fdc_generated(from: "Evento", purpose: QUERY_MULTIPLE)
  """
  ✨ List `EventoOcurrencia` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  eventoOcurrencias(
    """
    Filter condition to narrow down the query results.
    """
    where: EventoOcurrencia_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EventoOcurrencia_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EventoOcurrencia_Having
  ): [EventoOcurrencia!]! @fdc_generated(from: "EventoOcurrencia", purpose: QUERY_MULTIPLE)
  """
  ✨ List `EventoRecurrencia` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  eventoRecurrencias(
    """
    Filter condition to narrow down the query results.
    """
    where: EventoRecurrencia_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EventoRecurrencia_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EventoRecurrencia_Having
  ): [EventoRecurrencia!]! @fdc_generated(from: "EventoRecurrencia", purpose: QUERY_MULTIPLE)
  """
  ✨ List `EventoRelacion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  eventoRelaciones(
    """
    Filter condition to narrow down the query results.
    """
    where: EventoRelacion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [EventoRelacion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: EventoRelacion_Having
  ): [EventoRelacion!]! @fdc_generated(from: "EventoRelacion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Familia` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  familias(
    """
    Filter condition to narrow down the query results.
    """
    where: Familia_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Familia_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Familia_Having
  ): [Familia!]! @fdc_generated(from: "Familia", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Fase` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fases(
    """
    Filter condition to narrow down the query results.
    """
    where: Fase_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Fase_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Fase_Having
  ): [Fase!]! @fdc_generated(from: "Fase", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FaseMetodo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fasesMetodos(
    """
    Filter condition to narrow down the query results.
    """
    where: FaseMetodo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FaseMetodo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FaseMetodo_Having
  ): [FaseMetodo!]! @fdc_generated(from: "FaseMetodo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FaseRecurso` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fasesRecursos(
    """
    Filter condition to narrow down the query results.
    """
    where: FaseRecurso_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FaseRecurso_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FaseRecurso_Having
  ): [FaseRecurso!]! @fdc_generated(from: "FaseRecurso", purpose: QUERY_MULTIPLE)
  """
  ✨ List `FaseTecnica` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  fasesTecnicas(
    """
    Filter condition to narrow down the query results.
    """
    where: FaseTecnica_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [FaseTecnica_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: FaseTecnica_Having
  ): [FaseTecnica!]! @fdc_generated(from: "FaseTecnica", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Grupo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  grupos(
    """
    Filter condition to narrow down the query results.
    """
    where: Grupo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Grupo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Grupo_Having
  ): [Grupo!]! @fdc_generated(from: "Grupo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `IndicadorCapacidad` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  indicadoresCapacidad(
    """
    Filter condition to narrow down the query results.
    """
    where: IndicadorCapacidad_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [IndicadorCapacidad_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: IndicadorCapacidad_Having
  ): [IndicadorCapacidad!]! @fdc_generated(from: "IndicadorCapacidad", purpose: QUERY_MULTIPLE)
  """
  ✨ List `IndicadorCapacidadEstudiante` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  indicadoresCapacidadEstudiantes(
    """
    Filter condition to narrow down the query results.
    """
    where: IndicadorCapacidadEstudiante_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [IndicadorCapacidadEstudiante_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: IndicadorCapacidadEstudiante_Having
  ): [IndicadorCapacidadEstudiante!]! @fdc_generated(from: "IndicadorCapacidadEstudiante", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Matricula` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  matriculas(
    """
    Filter condition to narrow down the query results.
    """
    where: Matricula_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Matricula_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Matricula_Having
  ): [Matricula!]! @fdc_generated(from: "Matricula", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Metodo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  metodos(
    """
    Filter condition to narrow down the query results.
    """
    where: Metodo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Metodo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Metodo_Having
  ): [Metodo!]! @fdc_generated(from: "Metodo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Modulo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  modulos(
    """
    Filter condition to narrow down the query results.
    """
    where: Modulo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Modulo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Modulo_Having
  ): [Modulo!]! @fdc_generated(from: "Modulo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ModuloEstudiante` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  modulosEstudiantes(
    """
    Filter condition to narrow down the query results.
    """
    where: ModuloEstudiante_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ModuloEstudiante_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ModuloEstudiante_Having
  ): [ModuloEstudiante!]! @fdc_generated(from: "ModuloEstudiante", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ModuloVideo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  moduloVideos(
    """
    Filter condition to narrow down the query results.
    """
    where: ModuloVideo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ModuloVideo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ModuloVideo_Having
  ): [ModuloVideo!]! @fdc_generated(from: "ModuloVideo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Paquete` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  paquetes(
    """
    Filter condition to narrow down the query results.
    """
    where: Paquete_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Paquete_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Paquete_Having
  ): [Paquete!]! @fdc_generated(from: "Paquete", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PaqueteModulo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  paqueteModulos(
    """
    Filter condition to narrow down the query results.
    """
    where: PaqueteModulo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PaqueteModulo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PaqueteModulo_Having
  ): [PaqueteModulo!]! @fdc_generated(from: "PaqueteModulo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Personal` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  personals(
    """
    Filter condition to narrow down the query results.
    """
    where: Personal_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Personal_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Personal_Having
  ): [Personal!]! @fdc_generated(from: "Personal", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PersonalEspecialidad` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  personalEspecialidads(
    """
    Filter condition to narrow down the query results.
    """
    where: PersonalEspecialidad_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PersonalEspecialidad_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PersonalEspecialidad_Having
  ): [PersonalEspecialidad!]! @fdc_generated(from: "PersonalEspecialidad", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Plan` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  planes(
    """
    Filter condition to narrow down the query results.
    """
    where: Plan_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Plan_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Plan_Having
  ): [Plan!]! @fdc_generated(from: "Plan", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Post` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  posts(
    """
    Filter condition to narrow down the query results.
    """
    where: Post_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Post_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Post_Having
  ): [Post!]! @fdc_generated(from: "Post", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Publicacion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  publicacions(
    """
    Filter condition to narrow down the query results.
    """
    where: Publicacion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Publicacion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Publicacion_Having
  ): [Publicacion!]! @fdc_generated(from: "Publicacion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `PublicacionVideo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  publicacionVideos(
    """
    Filter condition to narrow down the query results.
    """
    where: PublicacionVideo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PublicacionVideo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PublicacionVideo_Having
  ): [PublicacionVideo!]! @fdc_generated(from: "PublicacionVideo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Recordatorio` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  recordatorios(
    """
    Filter condition to narrow down the query results.
    """
    where: Recordatorio_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Recordatorio_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Recordatorio_Having
  ): [Recordatorio!]! @fdc_generated(from: "Recordatorio", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Recurso` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  recursos(
    """
    Filter condition to narrow down the query results.
    """
    where: Recurso_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Recurso_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Recurso_Having
  ): [Recurso!]! @fdc_generated(from: "Recurso", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Rol` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  rols(
    """
    Filter condition to narrow down the query results.
    """
    where: Rol_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Rol_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Rol_Having
  ): [Rol!]! @fdc_generated(from: "Rol", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Sector` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  sectors(
    """
    Filter condition to narrow down the query results.
    """
    where: Sector_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Sector_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Sector_Having
  ): [Sector!]! @fdc_generated(from: "Sector", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Semestre` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  semestres(
    """
    Filter condition to narrow down the query results.
    """
    where: Semestre_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Semestre_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Semestre_Having
  ): [Semestre!]! @fdc_generated(from: "Semestre", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Tecnica` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tecnicas(
    """
    Filter condition to narrow down the query results.
    """
    where: Tecnica_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Tecnica_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Tecnica_Having
  ): [Tecnica!]! @fdc_generated(from: "Tecnica", purpose: QUERY_MULTIPLE)
  """
  ✨ List `TipoCarrera` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tipoCarreras(
    """
    Filter condition to narrow down the query results.
    """
    where: TipoCarrera_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TipoCarrera_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TipoCarrera_Having
  ): [TipoCarrera!]! @fdc_generated(from: "TipoCarrera", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Turno` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  turnos(
    """
    Filter condition to narrow down the query results.
    """
    where: Turno_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Turno_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Turno_Having
  ): [Turno!]! @fdc_generated(from: "Turno", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UnidadDidactica` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  unidadesDidacticas(
    """
    Filter condition to narrow down the query results.
    """
    where: UnidadDidactica_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UnidadDidactica_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UnidadDidactica_Having
  ): [UnidadDidactica!]! @fdc_generated(from: "UnidadDidactica", purpose: QUERY_MULTIPLE)
  """
  ✨ List `UnidadDidacticaEstudiante` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  unidadesDidacticasEstudiantes(
    """
    Filter condition to narrow down the query results.
    """
    where: UnidadDidacticaEstudiante_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [UnidadDidacticaEstudiante_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: UnidadDidacticaEstudiante_Having
  ): [UnidadDidacticaEstudiante!]! @fdc_generated(from: "UnidadDidacticaEstudiante", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ValorInstitucional` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  valoresInstitucionales(
    """
    Filter condition to narrow down the query results.
    """
    where: ValorInstitucional_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ValorInstitucional_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ValorInstitucional_Having
  ): [ValorInstitucional!]! @fdc_generated(from: "ValorInstitucional", purpose: QUERY_MULTIPLE)
  """
  ✨ List `VideoYoutube` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  videoYoutubes(
    """
    Filter condition to narrow down the query results.
    """
    where: VideoYoutube_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [VideoYoutube_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: VideoYoutube_Having
  ): [VideoYoutube!]! @fdc_generated(from: "VideoYoutube", purpose: QUERY_MULTIPLE)
}
