import {https,runWith} from 'firebase-functions/v1';
import {dataConnect} from '../core/dataConnectCore.js';
import {requirePermission} from '../core/permissions.js';
import {getIdFromKeyOutput} from '../core/userMappers.js';
import {parteChoices,teacherNames,todayInLima,validateParteInput,ParteSourceRow} from './handlers.js';
import {aggregateParte,groupParte,MetricsRecord,PlannedReportItem,ParteReportData,InformeRow} from './reportAnalytics.js';
import {VALUATION_FIELDS,valuationScore} from './valuations.js';
const graph=async<T>(query:string,variables:Record<string,unknown>={})=>(await dataConnect.executeGraphql<T,Record<string,unknown>>(query,{variables})).data;
const id=(value:unknown)=>{const n=Number(value);if(!Number.isInteger(n)||n<=0)throw new https.HttpsError('invalid-argument','Identificador inválido.');return n;};
const optionalId=(value:unknown)=>value==null||value===''?null:id(value);
const metadata=`id nombre moduloId modulo{titulo plan{carrera{tipoCarrera{nombre} actEconomica{familia{id titulo}}}}} grupo{semestreId archivado personal{id displayName user{nombre apellidoPaterno apellidoMaterno apellidos avatar}}}`;
type Person={id:number;displayName:string|null;user:{nombre:string|null;apellidoPaterno:string|null;apellidoMaterno:string|null;apellidos:string|null;avatar:string|null}|null};
type Group={id:number;nombre:string|null;moduloId:number;modulo:{titulo:string|null;plan:{carrera:{tipoCarrera:{nombre:string|null}|null;actEconomica:{familia:{id:number;titulo:string|null}|null}|null}|null}|null};grupo:{semestreId:number|null;archivado:boolean|null;personal:Person|null}};
type Stored=Omit<MetricsRecord,'docente'|'familia'|'familiaId'> & {docente:Person;grupoModulo:Group;unidadDidacticaId:number|null;unidadDidactica:{nombre:string|null}|null;actividad:{nombre:string|null}|null;actividadManual:string|null;firma?:string|null;observaciones?:string[]};
const RECORD_FIELDS=`id fecha grupoModuloId docenteId actividadProgramadaId actividadId unidadDidacticaId jornadaId tipoUnidad actividadManual matriculados asistentes silabo fichaActividad instrumentoEvaluacion material tareas silaboValor fichaActividadValor instrumentoEvaluacionValor materialValor tareasValor fechaActualizacion docente{id displayName user{nombre apellidoPaterno apellidoMaterno apellidos avatar}} unidadDidactica{nombre} actividad{nombre} grupoModulo{${metadata}}`;
export const REPORT_RECORDS_QUERY=`query ParteReportRecords($desde:Date!,$hasta:Date!,$offset:Int!){parteDiarioRegistros(where:{fecha:{ge:$desde,le:$hasta}},limit:500,offset:$offset,orderBy:{id:ASC}){${RECORD_FIELDS}}}`;
export const REPORT_SCHEDULE_QUERY=`query ParteReportSchedule($inicio:Timestamp!,$fin:Timestamp!,$offset:Int!){grupoModuloActividades(where:{inicio:{lt:$fin},fin:{gt:$inicio}},limit:500,offset:$offset,orderBy:{id:ASC}){id inicio fin actividadId grupoModuloId evento{estado} grupoModulo{${metadata}}}}`;
export const REPORT_JOURNEYS_QUERY=`query ParteReportJourneys($desde:Date!,$hasta:Date!,$offset:Int!){grupoModuloJornadas(where:{fecha:{ge:$desde,le:$hasta}},limit:500,offset:$offset,orderBy:{id:ASC}){id fecha tipo pendiente horas grupoModuloId evento{estado} grupoModulo{${metadata}}}}`;
export const REPORT_OPTIONS_QUERY=`query ParteReportOptions{semestres(limit:1000,orderBy:{titulo:DESC}){id titulo inicio fin} familias(limit:1000){id titulo} grupoModulos(limit:10000){${metadata}}}`;
export const SINGLE_REPORT_RECORD_QUERY=`query ParteReportRecord($id:Int!){parteDiarioRegistro(id:$id){${RECORD_FIELDS} firma observaciones}}`;
const dateOnly=(value:string)=>new Date(Date.parse(value)-5*3600000).toISOString().slice(0,10);
function filterInput(data:Record<string,unknown>){
 const desde=String(data.desde||''),hasta=String(data.hasta||'');
 for(const value of [desde,hasta])if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value)throw new https.HttpsError('invalid-argument','Selecciona fechas válidas.');
 if(desde>hasta||hasta>todayInLima()||Date.parse(hasta)-Date.parse(desde)>370*86400000)throw new https.HttpsError('invalid-argument','El período debe terminar como máximo hoy y abarcar hasta un año.');
 return {desde,hasta,semestreId:optionalId(data.semestreId),familiaId:optionalId(data.familiaId),docenteId:optionalId(data.docenteId)};
}
const family=(g:Group)=>g.modulo.plan?.carrera?.actEconomica?.familia??null;
const description=(g:Group,p:Person|null)=>({familiaId:family(g)?.id??null,familia:family(g)?.titulo||'Sin familia',docenteId:p?.id??0,docente:p?teacherNames(p).lista:'Sin docente'});
async function pages<T>(query:string,field:string,variables:Record<string,unknown>){const all:T[]=[];for(let offset=0;offset<20000;offset+=500){const result=await graph<Record<string,T[]>>(query,{...variables,offset}),batch=result[field];all.push(...batch);if(batch.length<500)return all;}throw new https.HttpsError('resource-exhausted','Reduce el período del reporte.');}
export async function reportRecord(recordId:number){const data=await graph<{parteDiarioRegistro:Stored|null}>(SINGLE_REPORT_RECORD_QUERY,{id:recordId});if(!data.parteDiarioRegistro)throw new https.HttpsError('not-found','El registro ya no existe.');return data.parteDiarioRegistro;}
export function reportRow(r:Stored){const names=teacherNames(r.docente),practiceType=/ocupacional/i.test(r.grupoModulo.modulo.plan?.carrera?.tipoCarrera?.nombre||'')?'ppp' as const:'efsrt' as const;
 return {recordId:r.id,key:`${r.grupoModuloId}:${r.actividadProgramadaId!=null?'a:'+r.actividadProgramadaId:'j:'+r.jornadaId}`,orden:1,grupoModuloId:r.grupoModuloId,moduloId:r.grupoModulo.moduloId,docenteId:r.docenteId,actividadProgramadaId:r.actividadProgramadaId,jornadaId:r.jornadaId,pendiente:r.actividadProgramadaId==null&&r.tipoUnidad==='curricular',practicaTipo:practiceType,docenteNombre:names.lista,docenteNombreCompleto:names.completo,avatar:r.docente.user?.avatar??null,turno:'',turnoOrden:0,modulo:r.grupoModulo.nombre||r.grupoModulo.modulo.titulo||'',tipoUnidad:r.tipoUnidad as 'curricular'|'ppp'|'efsrt',actividadManual:r.actividadManual||'',unidadDidacticaId:r.unidadDidacticaId,unidad:r.tipoUnidad==='curricular'?r.unidadDidactica?.nombre||'Pendiente de sílabo':r.tipoUnidad.toUpperCase(),actividadId:r.actividadId,actividad:r.tipoUnidad==='curricular'?r.actividad?.nombre||'Pendiente de sílabo':r.actividadManual||'',matriculados:r.matriculados,asistentes:r.asistentes,silabo:r.silabo,fichaActividad:r.fichaActividad,instrumentoEvaluacion:r.instrumentoEvaluacion,material:r.material,tareas:r.tareas,firma:r.firma??null,observaciones:r.observaciones??[],version:r.fechaActualizacion,valoraciones:Object.fromEntries(VALUATION_FIELDS.map(f=>[f,valuationScore(f,r[f])]))};
}
const scopeWhere=(filter:ReturnType<typeof filterInput>)=>['semestreId','familiaId','docenteId'].map(f=>`${f}:{${filter[f as 'semestreId']==null?'isNull:true':`eq:${filter[f as 'semestreId']}`}}`).join(',');
export async function buildParteReport(data:Record<string,unknown>):Promise<ParteReportData>{
 const f=filterInput(data),offset=Number(data.offset??0);if(!Number.isInteger(offset)||offset<0)throw new https.HttpsError('invalid-argument','Página inválida.');
 const range={inicio:f.desde+'T05:00:00Z',fin:new Date(Date.parse(f.hasta+'T05:00:00Z')+86400000).toISOString()};
 const [records,sessions,days,options,holidayData,notes]=await Promise.all([
  pages<Stored>(REPORT_RECORDS_QUERY,'parteDiarioRegistros',{desde:f.desde,hasta:f.hasta}),
  pages<{id:number;inicio:string;fin:string;actividadId:number;grupoModuloId:number;evento:{estado:string|null}|null;grupoModulo:Group}>(REPORT_SCHEDULE_QUERY,'grupoModuloActividades',range),
  pages<{id:number;fecha:string;tipo:string;pendiente:boolean;horas:number;grupoModuloId:number;evento:{estado:string|null}|null;grupoModulo:Group}>(REPORT_JOURNEYS_QUERY,'grupoModuloJornadas',{desde:f.desde,hasta:f.hasta}),
  graph<{semestres:{id:number;titulo:string|null}[];familias:{id:number;titulo:string|null}[];grupoModulos:Group[]}>(REPORT_OPTIONS_QUERY),
  graph<{eventos:{fechaInicio:string;estado:string|null;calendario:{activo:boolean|null}}[]}>(`query ParteReportHolidays($inicio:Timestamp!,$fin:Timestamp!){eventos(where:{tipoEvento:{eq:"feriado"},fechaInicio:{ge:$inicio,lt:$fin}},limit:5000){fechaInicio estado calendario{activo}}}`,range),
  graph<{parteDiarioInformes:InformeRow[]}>(`query ParteReportNotes($desde:Date!,$hasta:Date!){parteDiarioInformes(where:{fechaInicio:{eq:$desde},fechaFin:{eq:$hasta},${scopeWhere(f)}},limit:100,orderBy:{fechaActualizacion:DESC}){id titulo analisis recomendaciones fechaActualizacion}}`,{desde:f.desde,hasta:f.hasta}),
 ]);
 const matches=(g:Group,p:Person|null)=>(f.semestreId==null||g.grupo.semestreId===f.semestreId)&&(f.familiaId==null||family(g)?.id===f.familiaId)&&(f.docenteId==null||p?.id===f.docenteId);
 const holidays=new Set(holidayData.eventos.filter(e=>e.estado!=='cancelado'&&e.calendario.activo!==false).map(e=>dateOnly(e.fechaInicio)));
 const isWorking=(date:string)=>![0,6].includes(new Date(date+'T12:00:00Z').getUTCDay())&&!holidays.has(date);
 const plannedMap=new Map<string,PlannedReportItem>();
 for(const s of sessions){const g=s.grupoModulo,date=dateOnly(s.inicio);if(s.evento?.estado==='cancelado'||!isWorking(date)||!matches(g,g.grupo.personal))continue;const key=`${date}:${g.id}:a:${s.actividadId}`,old=plannedMap.get(key),hours=(Date.parse(s.fin)-Date.parse(s.inicio))/60000/45;plannedMap.set(key,{key,fecha:date,grupoModuloId:g.id,actividadId:s.actividadId,...description(g,g.grupo.personal),horas:(old?.horas||0)+hours});}
 for(const j of days){const g=j.grupoModulo;if(j.evento?.estado==='cancelado'||!isWorking(j.fecha)||!matches(g,g.grupo.personal)||j.tipo==='curricular'&&(!j.pendiente||[...plannedMap.values()].some(p=>p.fecha===j.fecha&&p.grupoModuloId===g.id)))continue;const key=`${j.fecha}:${g.id}:j:${j.id}`;plannedMap.set(key,{key,fecha:j.fecha,grupoModuloId:g.id,actividadId:null,...description(g,g.grupo.personal),horas:j.horas});}
 const filtered=records.filter(r=>matches(r.grupoModulo,r.docente)),metrics:MetricsRecord[]=filtered.map(r=>({...r,...description(r.grupoModulo,r.docente)})),planned=[...plannedMap.values()];
 const recordsSorted=[...filtered].sort((a,b)=>b.fecha.localeCompare(a.fecha)||teacherNames(a.docente).lista.localeCompare(teacherNames(b.docente).lista,'es')||b.id-a.id);
 return {desde:f.desde,hasta:f.hasta,total:aggregateParte(metrics,planned),porFamilia:groupParte(metrics,planned,'familia'),porDocente:groupParte(metrics,planned,'docente'),registros:recordsSorted.slice(offset,offset+100).map(r=>({id:r.id,fecha:r.fecha,docente:teacherNames(r.docente).lista,familia:family(r.grupoModulo)?.titulo||'Sin familia',modulo:r.grupoModulo.nombre||r.grupoModulo.modulo.titulo||'',unidad:r.tipoUnidad==='curricular'?r.unidadDidactica?.nombre||'Pendiente de sílabo':r.tipoUnidad.toUpperCase(),actividad:r.tipoUnidad==='curricular'?r.actividad?.nombre||'Pendiente de sílabo':r.actividadManual||'',matriculados:r.matriculados,asistentes:r.asistentes,version:r.fechaActualizacion})),registrosTotal:filtered.length,offset,informes:notes.parteDiarioInformes,opciones:{semestres:options.semestres,familias:options.familias,docentes:[...new Map([...options.grupoModulos.map(g=>g.grupo.personal),...records.map(r=>r.docente)].filter((p):p is Person=>p!=null).map(p=>[p.id,{id:p.id,nombre:teacherNames(p).lista}])).values()].sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'))}};
}
export const getParteReporte=runWith({timeoutSeconds:180,memory:'512MB'}).https.onCall(async(data,context)=>{await requirePermission(context,'reportes-parte-diario','view');return buildParteReport(data||{});});
export const getParteReporteRegistro=https.onCall(async(data,context)=>{await requirePermission(context,'reportes-parte-diario','view');const record=await reportRecord(id(data?.id));return {fecha:record.fecha,row:reportRow(record)};});
export const getParteReporteOpciones=https.onCall(async(data,context)=>{await requirePermission(context,'reportes-parte-diario','view');const record=await reportRecord(id(data?.id));return {unidades:await parteChoices(record.grupoModulo.moduloId,record.grupoModuloId)};});
export const saveParteReporteRegistro=runWith({timeoutSeconds:120}).https.onCall(async(data,context)=>{await requirePermission(context,'reportes-parte-diario','edit');const record=await reportRecord(id(data?.id)),row=reportRow(record);if(record.fecha>todayInLima())throw new https.HttpsError('failed-precondition','No se pueden editar registros futuros.');const payload={...await validateParteInput(data,row as ParteSourceRow),actualizadoPor:context.auth!.uid,fechaActualizacion:new Date().toISOString()},allow=Object.keys(payload).join(' ');
 await graph(`mutation UpdateParteReport($id:Int!,$version:Timestamp!,$data:ParteDiarioRegistro_Data! @allow(fields:"${allow}")) @transaction {parteDiarioRegistro_update(first:{where:{id:{eq:$id},fechaActualizacion:{eq:$version}}},data:$data) @check(expr:"this != null",message:"El registro cambió; actualiza el reporte.")}`,{id:record.id,version:row.version,data:payload});return {ok:true};});
export const deleteParteDiarioRegistro=https.onCall(async(data,context)=>{await requirePermission(context,'parte-diario','delete');const record=await reportRecord(id(data?.id));if(data?.version!==record.fechaActualizacion)throw new https.HttpsError('aborted','El registro cambió; actualiza la lista.');await graph(`mutation DeleteParteRecord($id:Int!,$version:Timestamp!) @transaction {parteDiarioRegistro_delete(first:{where:{id:{eq:$id},fechaActualizacion:{eq:$version}}}) @check(expr:"this != null",message:"El registro cambió; actualiza la lista.")}`,{id:record.id,version:record.fechaActualizacion});return {ok:true};});
export const saveParteInforme=https.onCall(async(data,context)=>{await requirePermission(context,'reportes-parte-diario','edit');const filter=filterInput(data||{}),titulo=String(data?.titulo||'').trim(),analisis=String(data?.analisis||'').trim(),recomendaciones=String(data?.recomendaciones||'').trim();if(!titulo||titulo.length>200||analisis.length>20000||recomendaciones.length>20000)throw new https.HttpsError('invalid-argument','Revisa el título y la longitud del informe.');const payload={fechaInicio:filter.desde,fechaFin:filter.hasta,semestreId:filter.semestreId,familiaId:filter.familiaId,docenteId:filter.docenteId,titulo,analisis,recomendaciones,actualizadoPor:context.auth!.uid,fechaActualizacion:new Date().toISOString()};let recordId=optionalId(data?.id);
 if(recordId){const old=(await graph<{parteDiarioInforme:InformeRow&{fechaInicio:string;fechaFin:string;semestreId:number|null;familiaId:number|null;docenteId:number|null}|null}>(`query ParteInforme($id:Int!){parteDiarioInforme(id:$id){id fechaInicio fechaFin semestreId familiaId docenteId titulo analisis recomendaciones fechaActualizacion}}`,{id:recordId})).parteDiarioInforme;if(!old)throw new https.HttpsError('not-found','El informe ya no existe.');if(data.version!==old.fechaActualizacion)throw new https.HttpsError('aborted','El informe cambió; actualiza la lista.');if(old.fechaInicio!==filter.desde||old.fechaFin!==filter.hasta||old.semestreId!==filter.semestreId||old.familiaId!==filter.familiaId||old.docenteId!==filter.docenteId)throw new https.HttpsError('invalid-argument','Conserva el período y los filtros originales del informe.');await graph(`mutation UpdateParteInforme($id:Int!,$version:Timestamp!,$data:ParteDiarioInforme_Data! @allow(fields:"${Object.keys(payload).join(' ')}")) @transaction {parteDiarioInforme_update(first:{where:{id:{eq:$id},fechaActualizacion:{eq:$version}}},data:$data) @check(expr:"this != null",message:"El informe cambió; actualiza la lista.")}`,{id:recordId,version:old.fechaActualizacion,data:payload});}
 else {const result=await graph<{parteDiarioInforme_insert:unknown}>(`mutation InsertParteInforme($data:ParteDiarioInforme_Data! @allow(fields:"${Object.keys(payload).join(' ')} creadoPor fechaCreacion")){parteDiarioInforme_insert(data:$data)}`,{data:{...payload,creadoPor:context.auth!.uid,fechaCreacion:payload.fechaActualizacion}});recordId=id(getIdFromKeyOutput(result.parteDiarioInforme_insert));}
 return {ok:true,id:recordId};});
