import { VALUATION_FIELDS, ValuationField, valuationScore } from './valuations.js';
export type MetricsRecord = {id:number;fecha:string;grupoModuloId:number;docenteId:number;familiaId:number|null;docente:string;familia:string;actividadId:number|null;actividadProgramadaId:number|null;jornadaId:number|null;tipoUnidad:string;matriculados:number;asistentes:number|null;fechaActualizacion:string} & Record<ValuationField,string> & Partial<Record<`${ValuationField}Valor`,number|null>>;
const recordScore=(r:MetricsRecord,field:ValuationField)=>{const score=r[`${field}Valor`];return typeof score==='number'&&Number.isInteger(score)&&score>=0&&score<=4?score:valuationScore(field,r[field]);};
export type PlannedReportItem={key:string;fecha:string;grupoModuloId:number;docenteId:number;familiaId:number|null;docente:string;familia:string;actividadId:number|null;horas:number};
export type ParteMetrics={registros:number;programadas:number;cobertura:number|null;jornadasConAsistencia:number;jornadasSinAsistencia:number;matriculadosAcumulados:number;asistentesAcumulados:number;inasistenciasAcumuladas:number;asistencia:number|null;actividadesRegistradas:number;actividadesProgramadas:number;avance:number|null;valoraciones:Record<ValuationField,{promedio:number|null;cantidad:number;distribucion:number[]}>;indice:number|null;asistenciasDiscordantes:number};
export const recordKey=(r:MetricsRecord)=>`${r.fecha}:${r.grupoModuloId}:${r.actividadProgramadaId!=null?'a:'+r.actividadProgramadaId:'j:'+r.jornadaId}`;
export function aggregateParte(records:MetricsRecord[],planned:PlannedReportItem[]):ParteMetrics{
 const expected=new Set(planned.map(p=>`${p.fecha}:${p.grupoModuloId}`)),registered=new Set(records.map(r=>`${r.fecha}:${r.grupoModuloId}`));
 const expectedActivities=new Set(planned.filter(p=>p.actividadId!=null).map(p=>`${p.grupoModuloId}:${p.actividadId}`));
 const actualActivities=new Set(records.filter(r=>r.tipoUnidad==='curricular'&&r.actividadId!=null).map(r=>`${r.grupoModuloId}:${r.actividadId}`).filter(key=>expectedActivities.has(key)));
 const attendance=new Map<string,MetricsRecord>(),counts=new Map<string,Set<number>>();
 for(const r of records){const key=`${r.fecha}:${r.grupoModuloId}`;if(!counts.has(key))counts.set(key,new Set());if(r.asistentes==null)continue;counts.get(key)!.add(r.asistentes);const old=attendance.get(key);if(!old||Date.parse(r.fechaActualizacion)>Date.parse(old.fechaActualizacion)||r.fechaActualizacion===old.fechaActualizacion&&r.id>old.id)attendance.set(key,r);}
 const enrolled=[...attendance.values()].reduce((n,r)=>n+r.matriculados,0),present=[...attendance.values()].reduce((n,r)=>n+r.asistentes!,0);
 const ratings=Object.fromEntries(VALUATION_FIELDS.map(field=>{const values=records.map(r=>recordScore(r,field)).filter((score):score is number=>score!=null);return [field,{promedio:values.length?values.reduce((n,s)=>n+s,0)/values.length:null,cantidad:values.length,distribucion:[0,1,2,3,4].map(score=>values.filter(s=>s===score).length)}];})) as ParteMetrics['valoraciones'];
 const allScores=VALUATION_FIELDS.flatMap(field=>records.map(r=>recordScore(r,field)).filter((score):score is number=>score!=null));
 return {registros:records.length,programadas:expected.size,cobertura:expected.size?[...registered].filter(k=>expected.has(k)).length/expected.size*100:null,jornadasConAsistencia:attendance.size,jornadasSinAsistencia:counts.size-attendance.size,matriculadosAcumulados:enrolled,asistentesAcumulados:present,inasistenciasAcumuladas:enrolled-present,asistencia:enrolled>0?present/enrolled*100:null,actividadesRegistradas:actualActivities.size,actividadesProgramadas:expectedActivities.size,avance:expectedActivities.size?actualActivities.size/expectedActivities.size*100:null,valoraciones:ratings,indice:allScores.length?allScores.reduce((n,s)=>n+s,0)/allScores.length:null,asistenciasDiscordantes:[...counts.values()].filter(s=>s.size>1).length};
}
export function groupParte(records:MetricsRecord[],planned:PlannedReportItem[],dimension:'docente'|'familia'){
 const identity=(r:MetricsRecord|PlannedReportItem)=>dimension==='docente'?r.docenteId:r.familiaId??0;
 const ids=new Set([...records,...planned].map(identity));
 return [...ids].map(id=>{const rs=records.filter(r=>identity(r)===id),ps=planned.filter(p=>identity(p)===id),first=rs[0]||ps[0];return {id,nombre:dimension==='docente'?first.docente:first.familia,...aggregateParte(rs,ps)};}).sort((a,b)=>a.nombre.localeCompare(b.nombre,'es'));
}
export type InformeRow={id:number;titulo:string;analisis:string;recomendaciones:string;fechaActualizacion:string};
export type ParteReportData={desde:string;hasta:string;total:ParteMetrics;porFamilia:ReturnType<typeof groupParte>;porDocente:ReturnType<typeof groupParte>;registros:{id:number;fecha:string;docente:string;familia:string;modulo:string;unidad:string;actividad:string;matriculados:number;asistentes:number|null;version:string}[];registrosTotal:number;offset:number;informes:InformeRow[];opciones:{semestres:{id:number;titulo:string|null;inicio?:string|null;fin?:string|null}[];familias:{id:number;titulo:string|null}[];docentes:{id:number;nombre:string}[]}};
